[platformio]
src_dir = ph_titrator

[env:unihiker]
platform = https://github.com/DFRobot/platform-unihiker.git
board = unihiker_k10
framework = arduino
board_build.partitions = ph_titrator/partitions.csv
lib_deps =
    madhephaestus/ESP32Servo@^3.2.1
build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
    -DModel=None
monitor_speed = 115200
